version: "3.0"

services:
  api:
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - .:/home/workspace
    build: .
    # command: [
    #    "python",
    #    "src/main.py",
    # ]
    tty: true
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "fastapi"
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 9000:3306
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data: