version: "3.0"

services:
  api:
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - .:/home/workspace
    build: .
    command: [
       "uvicorn",
       "src.main:app",
       "--reload",
       "--host",
       "0.0.0.0",
       "--port",
       "8080"
    ]
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "fastapi"
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
      LC_ALL: "ja_JP.UTF-8"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 9000:3306
volumes:
  mysql_data: